name: flutter_app_builder
description: Build your Flutter app via Dart.
version: 0.2.1
homepage: https://github.com/leanflutter/flutter_distributor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  pub_semver: ^2.1.0
  pubspec_parse: 1.1.0
