name: flutter_app_builder
description: Build your Flutter app via Dart.
version: 0.3.2
homepage: https://distributor.leanflutter.org
repository: https://github.com/leanflutter/flutter_distributor/tree/main/packages/flutter_app_builder

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  glob: ^2.1.1
  pub_semver: ^2.1.0
  pubspec_parse: ^1.1.0
  recase: ^4.1.0
  shell_executor: ^0.1.3
dev_dependencies:
  dependency_validator: ^3.0.0
  test: ^1.23.1
