name: flutter_distributor
description: Package your Flutter app into OS-specific bundles (.dmg, .exe, etc.) via Dart or the command line.
version: 0.0.9
homepage: https://github.com/leanflutter/flutter_distributor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  app_package_maker: ^0.0.9
  app_package_publisher: ^0.0.9
  args: ^2.2.0
  colorize: ^3.0.0
  console_bars: ^1.0.3
  dio: ^4.0.4
  flutter_app_builder: ^0.0.9
  flutter_app_packager: ^0.0.9
  flutter_app_publisher: ^0.0.9
  logging: ^1.0.2
  path: ^1.8.1
  pub_semver: ^2.1.0
  pubspec_parse: ^1.2.0
  yaml: ^3.1.0

# dependency_overrides:
#   app_package_maker:
#     path: ../app_package_maker
#   app_package_maker_aab:
#     path: ../app_package_maker_aab
#   app_package_maker_apk:
#     path: ../app_package_maker_apk
#   app_package_maker_deb:
#     path: ../app_package_maker_deb
#   app_package_maker_dmg:
#     path: ../app_package_maker_dmg
#   app_package_maker_exe:
#     path: ../app_package_maker_exe
#   app_package_maker_ipa:
#     path: ../app_package_maker_ipa
#   app_package_maker_zip:
#     path: ../app_package_maker_zip
#   app_package_parser:
#     path: ../app_package_parser
#   app_package_parser_apk:
#     path: ../app_package_parser_apk
#   app_package_publisher:
#     path: ../app_package_publisher
#   app_package_publisher_fir:
#     path: ../app_package_publisher_fir
#   app_package_publisher_pgyer:
#     path: ../app_package_publisher_pgyer
#   flutter_app_builder:
#     path: ../flutter_app_builder
#   flutter_app_packager:
#     path: ../flutter_app_packager
#   flutter_app_publisher:
#     path: ../flutter_app_publisher

executables:
  flutter_distributor: main
