name: flutter_distributor
description: A powerful and efficient tool for packaging and publishing your applications with ease.
version: 0.4.6
homepage: https://distributor.leanflutter.dev
repository: https://github.com/leanflutter/flutter_distributor/tree/main/packages/flutter_distributor
issue_tracker: https://github.com/leanflutter/flutter_distributor/issues

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  unified_distributor: ^0.1.0

dev_dependencies:
  mostly_reasonable_lints: ^0.1.2

executables:
  flutter_distributor: main
