name: flutter_distributor
description: A complete tool for packaging and publishing your Flutter apps.
version: 0.3.8
homepage: https://distributor.leanflutter.org
repository: https://github.com/leanflutter/flutter_distributor/tree/main/packages/flutter_distributor
issue_tracker: https://github.com/leanflutter/flutter_distributor/issues

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  ansicolor: ^2.0.1
  app_package_maker: ^0.3.6
  app_package_publisher: ^0.3.6
  args: ^2.2.0
  charset: ^2.0.1
  dio: ^5.3.4
  flutter_app_builder: ^0.3.7
  flutter_app_packager: ^0.3.7
  flutter_app_publisher: ^0.3.6
  logging: ^1.0.2
  path: ^1.8.1
  pubspec_parse: ^1.1.0
  shell_executor: ^0.1.5
  shell_uikit: ^0.1.1
  yaml: ^3.1.0

dev_dependencies:
  dependency_validator: ^3.0.0
  test: ^1.23.1

executables:
  flutter_distributor: main
