name: flutter_distributor
description: A complete tool for packaging and publishing your Flutter apps.
version: 0.2.0
homepage: https://github.com/leanflutter/flutter_distributor

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  app_package_maker: ^0.1.3
  app_package_publisher: ^0.1.5
  args: ^2.2.0
  colorize: ^3.0.0
  dio: ^4.0.4
  flutter_app_builder: ^0.1.8
  flutter_app_packager: ^0.1.9
  flutter_app_publisher: ^0.2.0
  logging: ^1.0.2
  path: ^1.8.1
  pub_semver: ^2.1.0
  pubspec_parse: ^1.1.0
  yaml: ^3.1.0

executables:
  flutter_distributor: main
