name: shell_uikit
description: A simple shell ui kit.
version: 0.1.1
homepage: https://distributor.leanflutter.dev
repository: https://github.com/leanflutter/flutter_distributor/tree/main/packages/shell_uikit

environment:
  sdk: ">=2.16.0 <4.0.0"

dev_dependencies:
  dependency_validator: ^3.0.0
