name: app_package_publisher
description: App package publisher
version: 0.1.5
homepage: https://github.com/leanflutter/flutter_distributor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  pubspec_parse: ^1.1.0
  yaml: ^3.1.0
