name: app_package_maker_dmg
description: Create a dmg package for your app.
version: 0.2.1
homepage: https://github.com/leanflutter/flutter_distributor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  app_package_maker: ^0.2.1
