name: parse_app_package
description: Parse app package
version: 0.3.2
homepage: https://distributor.leanflutter.org
repository: https://github.com/leanflutter/flutter_distributor/tree/main/packages/parse_app_package

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  app_package_parser: ^0.2.3
  archive: ^3.1.5
  args: ^2.2.0
  shell_executor: ^0.1.2
  xml: ^6.3.0

executables:
  parse_app_package: main

dev_dependencies:
  dependency_validator: ^3.0.0
