name: app_package_maker_msix
description: Create a msix package for your app.
version: 0.1.9
homepage: https://github.com/leanflutter/flutter_distributor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  app_package_maker: ^0.1.3
  io: ^1.0.3
  msix: ^3.3.2
  path: ^1.8.1

# dependency_overrides:
#   app_package_maker:
#     path: ../app_package_maker
