name: app_package_maker_exe
description: Create a exe package for your app.
version: 0.1.6
homepage: https://github.com/leanflutter/flutter_distributor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  app_package_maker: ^0.1.3
  io: ^1.0.3
  liquid_engine: ^0.2.2
  path: ^1.8.1
