name: app_package_parser_ipa
description: Parse ipa package.
version: 0.1.3
homepage: https://github.com/leanflutter/flutter_distributor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  app_package_parser: ^0.1.3
  archive: ^3.1.5
  xml: ^5.1.2

# dependency_overrides:
#   app_package_parser:
#     path: ../app_package_parser
