name: app_package_maker
description: App package maker
version: 0.2.9
homepage: https://github.com/leanflutter/flutter_distributor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  mustache_template: ^2.0.0
  pub_semver: ^2.1.0
  pubspec_parse: ^1.1.0
  yaml: ^3.1.0

dev_dependencies:
  dependency_validator: ^3.0.0
