name: "HelloWorld: Build"

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened]

jobs:
  build-aab:
    name: Build AAB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.1
      - uses: bluefireteam/melos-action@v3
      - run: |
          dart ../../packages/flutter_distributor/bin/main.dart package \
            --platform=android \
            --targets aab
        working-directory: examples/hello_world

  build-apk:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.1
      - uses: bluefireteam/melos-action@v3
      - run: |
          dart ../../packages/flutter_distributor/bin/main.dart package \
            --platform=android \
            --targets apk
        working-directory: examples/hello_world

  build-appimage:
    name: Build AppImage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.1
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libfuse2
      - uses: bluefireteam/melos-action@v3
      - run: |
          wget -O appimagetool "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
          chmod +x appimagetool
          mv appimagetool /usr/local/bin/
      - run: |
          dart ../../packages/flutter_distributor/bin/main.dart package \
            --platform=linux \
            --targets appimage
        working-directory: examples/hello_world

  build-deb:
    name: Build DEB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.1
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - uses: bluefireteam/melos-action@v3
      - run: |
          dart ../../packages/flutter_distributor/bin/main.dart package \
            --platform=linux \
            --targets deb
        working-directory: examples/hello_world
