name: flutter_app_packager
description: Package your Flutter app into OS-specific bundles (.dmg, .exe, etc.) via Dart or the command line.
version: 0.3.0
homepage: https://github.com/leanflutter/flutter_distributor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  app_package_maker: ^0.3.0
  archive: ^3.1.5
  glob: ^2.1.1
  io: ^1.0.3
  liquid_engine: ^0.2.2
  path: ^1.8.1
  shell_executor: ^0.1.1
dev_dependencies:
  dependency_validator: ^3.0.0
