name: flutter_app_packager
description: Package your Flutter app into OS-specific bundles (.dmg, .exe, etc.) via Dart or the command line.
version: 0.2.3
homepage: https://github.com/leanflutter/flutter_distributor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  app_package_maker: ^0.2.1
  app_package_maker_aab: ^0.2.1
  app_package_maker_apk: ^0.2.1
  app_package_maker_appimage: ^0.0.1
  app_package_maker_deb: ^0.2.1
  app_package_maker_dmg: ^0.2.3
  app_package_maker_exe: ^0.2.1
  app_package_maker_ipa: ^0.2.1
  app_package_maker_msix: ^0.2.1
  app_package_maker_zip: ^0.2.1
  args: ^2.2.0
  yaml: ^3.1.0
